src/omero_cli_render.py
test/integration/clitest/test_render.py

Switches the logic of the `test` command to perform cross group querying. Without this or a similar change you must know the group of the data you want to test before executing the command.
Documentation has also been updated to reflect the impact of the `--skipthumbs` and `--force` command line arguments on the command.
/cc @emilroz

Cross group querying and `test` documentation

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

Replaces #3 (closed), rebased to latest `master` branch.
- Bugfix for the `info` command
- Rename `edit` command to `set`
- Enable setting rendering settings also on Project and Dataset level.
Test:
- Check that the `info` command works
- Check that previously called`edit` command is now called `set` and it still works (calling `edit` should provide a reasonable error message about the renaming).
- Try to set rendering settings for a Project and a Dataset and make sure that works.
I think the easiest way to test the plugin is:
- Download the plugin: https://raw.githubusercontent.com/dominikl/omero-cli-render/8d4a8f94ae3f60fec8f15e7a2a0d26c053d1406f/src/omero_cli_render.py
- Put in a directory called `omero/plugins` e. g. `~/test/omero/plugins` 
- Add the parent directory to the …

Fix render plugin

---

src/omero_cli_render.py

Cleans up some issues with the render plugin, see https://trello.com/c/hPoU5BbW/139-render-plugin-follow-up 
- Removes the `--copy` flag for the `set` command. It is just confusing and the workflow can easily be achived by running `set` on an image and then run the `copy` command afterwards.
- If a channel was not specified in the renderings settings yml/json it was disabled. That's not an expected behaviour. It actually is an issue of the `set_active_channels` method in the gateway https://github.com/openmicroscopy/openmicroscopy/blob/1ecd0f0f96f39f1e8575d3d424e479ac2bda3dc8/components/tools/OmeroPy/src/omero/gateway/__init__.py#L8471 , but this PR adds a workaround for that to the render plugin
- Improves the help a bit, by replacing misleading/wrong information and moving the examples …

General cleanup

---

src/omero_cli_render.py

Makes sure that all services are closed again but not the session itself by calling `gateway.close(hard=False)`. Without that services are left open and the execution will fail after some time when used in parallel and/or on large datasets (Resource limit of the session exceeded).
Test:
- Generally: Execute some render plugin commands ('test', 'info', etc.) and check they still work.
- Bugfix: That's a bit tricky. Run render 'set' in parallel (5 threads) and check that it doesn't fail. Without this PR it usually failed within 3 hours.

Close Blitzgateway services

---

src/omero_cli_render.py

Adds a `--disable` option to the `set` command, which if set, deactivates all channels which are not specified in the rendering settings file.
**Test:**
For an image with e.g. 3 active channels: Create a renderings settings json/yml, which specifies 2 channels. Run the `set` command without `--disable` flag:
`./omero set Image:123 settings.json` - Check that the settings are applied and the third channel is still active.
Change the rendering settings a bit, then use the `--disable` flag:
`./omero set --disable Image:123 settings.json` - Check that the settings are applied but this time the third channel is deactivated.

Add disable option to set command

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

This PR fixes some bugs I noticed while trying to export ('render info') and apply ('render set') the rendering settings of idr0044:
- The channel index was off by 1 (when setting the name and activate/deactivate)
- 'info' command output used 0-based index, whereas the 'set' command expects 1-based index for the channels
- start and end values specified in the yaml were ignored (when setting the rendering settings)
- Instead of start/end the min/max values specified in the yaml were set as window start/end.
- If a channel is not specified in the yaml it is deactivated by the the `set_active_channels` method. I added a workround earlier, which is not buggy (afaik) but I changed it a bit, so its clearer and safer.
**Test**: With this PR it should now be possible to adjust the rendering …

Some bugfixes

---

src/omero_cli_render.py

Follow up to #15 .
- Moved the version check code into a separate function
- Check the version in the ChannelObject directly, so other code should not be affected by the versioning.

Improve versioning code

---

test/integration/clitest/test_render.py

This PR focues on reduce the time spent on integration tests by Travis CI.
The major change is  in 694ce8e. Previously `create_image` was creating multiple images in a SPW and a PDI structure for every integration test. This commit allows to pass a `target_name` so that the container hierarchy is only created when required by the test, defaulting to a simple orphaned image import.
Tests are also reviewed and reduced so that the functionalities are still covered without going explicitly through all combinations of target/rendering settings. The broken tests (which were still executed on every PR) are replaced by testing the passing scenario of 2-channel images in various target containers which does not have the limitation reported previously.
All tests should pass and the overall time …

Integration tests review

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

Fixes #16 
Allows specifying defaultZ/defaultT, as `z` and `t` (1 based index).

Enable setting defaultZ/defaultT

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

Follow-up of #23, this adds some validation and error handling when default Z/T planes are passed via the `render set` command.
- if the plane index is completely invalid (0 or less or non-integer value), fails with an error code
- if the plane index is large than the image dimension, two behaviors are implemented depending on whether a lenient `--ignore-errors` flag is passed to the command
* by default (strict), the assumption is that the rendering dictionary matches the image dimensions and an error is thrown
* if `--ignore-errors` is passed, the default plane is ignored
Integration tests are also added to cover the two behaviors described above.

Default Z/T planes: validation

---

src/omero_cli_render.py

Fixes #19 
Makes the 'info' command output yamllint compatible.
**Test**:
`./omero render info --style yaml Image:123  > test.yml`
Then `yamllint test.yml` shouldn't report any errors/warnings.

Make 'info' output yamllint compatible

---

src/omero_cli_render.py

- Make sure rendering engines are closed (`set` command). I wonder if that caused the render plugin to fall over if it was running repeatedly for a long time reusing the same session.
- Simplify the `copy` command implementation a bit (was unnecessarily split over three different methods).
- Improve the docs a little bit.

Fix and docs

---

.travis.yml
setup.py
src/omero_cli_render.py
test/integration/clitest/cli.py
test/integration/clitest/info.json
test/integration/clitest/test_render.py

This PR updates `omero-cli-render` to be Python 3 compatible.
- run `futurize` on the code
- declare `omero-py`, `future` as dependencies and switch to `mox3`
Travis should test the installation of the plugin as well as run the integration tests against the current Python 3 `omero-test-infra` environment.
Proposed tag `0.5.dev1`

Add Python3 support to the render plugin

---

src/omero_cli_render.py
test/integration/clitest/info.plain
test/integration/clitest/test_render.py

See https://github.com/ome/omero-cli-render/pull/31#issuecomment-555949322
- 49b8cad adds a new integration test covering the `--style plain` output of the `info` subcommand including some assertion that there is no printing error in the stderr
- ff001f6 fixes the printing error

Add integration test for the info subcommand with plain style

---

src/omero_cli_render.py
test/unit/test_set.py

While working on a feature allowing to process multiple images with multiple rendering settings, I found it useful to refactor the logic of the `render set` command dealing with loading and parsing rendering settings from a source (object or file on disk).
The changes included in this PR should not changing behavior, include some cleanup (`print` ->`debug`) as well as unit tests starting to cover some of the individual functionalities

render set: helper refactoring

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

Previously, ```img.set_active_channels(reactivatechannels)``` was turning OFF the channels
that were active and edited in the previous set_active_channels() call.
To test, find an Image with 3 Channels, all Active.
Run:
```
$ omero render set Image:1 settings.yml
```
with less than 3 Channels specified, e.g.
settings.yml
```yaml
---
channels:
1:
active: true
start: 0
end: 255
greyscale: false
version: 2
```
This should only edit the first Channel. All 3 channels should stay Active.

Fix reactivate channels

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

This PR attempts to fix the behavior of the current render plugin when a YML/JSON file contains rendering settings (color, start/end window) for both active and inactive channels. In the current scenario, the rendering settings for the inactive channels are silently ignored. fc9cee4  contains a failing test capturing this behavior.
This issue was the primary motivation behind the `omero.gateway` API introduced in https://github.com/ome/openmicroscopy/pull/5955. With this change, rendering settings should be applied independently of the active state of the channel if specified via the configuration file.
Opening this as a behavior change of the plugin as I consider the current implementation as faulty and inconsistent with the fact channel names are set unconditionally. If backward …

Set rendering settings for inactive channels

---

src/omero_cli_render.py
test/unit/test_set.py

Reported by @jburel. In the absence of an explicit `version` key in the rendering file, the detection logic in `_getversion()` is currently checking the presence of `start/end` vs `min/max` keys (as the semantics of these has changed since version 1 and 2) and unconditionally returning `0` (undefined version) in absence of any of these keys. This means a simple rendering file as the following is currently detected as invalid:
```
---
channels:
1:
label: 'DNA' 
```
ab081ac fixes this issue by returning the version of the latest specification version (`2`)in this case.  28a10df also increases the type and the range of supported versions when the `version` argument is present. Several unit tests have been added that should test various YML files and the plugin expectation when loading these. …

Version detection fix

---

src/omero_cli_render.py

The `info` command creates a `RenderObject` which loads a RenderingEngine but doesn't close it. When you run it on a large Plate you soon hit an OutOfMemory exception. This PR closes the RenderingEngine again. 
~~The PR also adds a `thumb` command which generates rendering settings (if there aren't any yet) and creates the thumbnails. Without it one has to run first `render info` and then `test --thumb`.~~

Make sure RE is closed

---

src/omero_cli_render.py

Adds `version: 2` to the embedded examples of renderdefs.

Include version in examples

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

This adds support for setting `min` and `max`.
E.g:
```
---
channels:
1:
active: true
end: 2000.0
start: 150.0
min: 10
max: 3000
greyscale: false
version: 2
```
Both `min` and `max` are optional and don't depend on each other.
To test:
- `omero render set Image:1 settings.yml`
- Then Refresh right panel in webclient, or refresh iviewer and click Min/Max to set rendering settings to the new min/max values.
cc @pwalczysko 
Based on example code from:
https://github.com/ome/omero-scripts/pull/103/files#diff-70c904f67c4f0348841edf1ebdac7c32d8914ab87ac05a0a8f9948d47a8b94d7R195

Support min/max to update StatsInfo

---

src/omero_cli_render.py

Also print out the image id in the `test` command output. Test: Run `omero render test Image:123` and check that the correct image id is printed. Note: This obviously makes more sense if run on Dataset, Plate, etc. level.

test command: also print image id

---

setup.py
test/integration/clitest/cli.py

See https://github.com/ome/omero-py/pull/385
- Update tests requirements to require OMERO.py 5.17.0 which deprecates the usage of mox3 for running integration tests
- Consume omero.testlib.cli.AbstractCLITest

Remove mox3 from the test requirements

---

setup.py

Depends on https://github.com/ome/omero-test-infra/pull/68
- deprecate the PyTest command and use pytest directly to run the tests

Integration tests: call pytest directly

---

src/omero_cli_render.py
test/integration/clitest/test_render.py

This PR aims to fix the scenario where an user runs `omero render test --thumb` on an OMERO Image with no associated `RenderingDef` and `Thumbnail` object. With the current version of the CLI render plugin, the server should throw an exception similar to:
```
serverStackTrace = ome.conditions.SecurityViolation: isGraphCriticalCheck: not enough context
at ome.security.basic.CurrentDetails.isGraphCritical(CurrentDetails.java:220)
at ome.security.basic.BasicSecuritySystem.isGraphCritical(BasicSecuritySystem.java:352)
at ome.services.ThumbnailCtx.isExtendedGraphCritical(ThumbnailCtx.java:728)
at ome.services.ThumbnailBean.errorIfNullRenderingDef(ThumbnailBean.java:768)
at ome.services.ThumbnailBean.errorIfNullPixelsAndRenderingDef(ThumbnailBean.java:748)
at …
```

Fix thumbnail generation with missing rendering definition

---

src/omero_cli_render.py

Closes #66
The underlying code change has been applied in #43 and released since `omero-cli-render 0.6.0` but the help was never updated and was still documenting the previous behavior.

omero render set: clarify help around settings for disabled channels

---

.gitignore
src/omero_cli_render.py

I just need a better way to export rendering settings from a pilot and import them again on IDR prod, the approach via Ids doesn't work, because they are obviously different on the machines. This PR adds an `export` and `impo`(rt) command, which exports rendering settings as yml files (<dataset name><separator><image name>.yml) resp. imports them again. This can be done either one per dataset, or traverse datasets and export one renderings settings yml for each image.
It only works for Project/Dataset/Image for now, not for Screen/Plate/Well, yet. I'll just open that as draft PR, if anyone else want to use it, install it from my branch. Assume it won't be merged anyway.

Add export and impo(rt) commands
